FROM node:20-alpine

RUN apk add --no-cache curl bash git

WORKDIR /app

RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

COPY app/package.json app/bun.lock ./
RUN bun install

COPY app/ .

COPY .git ./.git

EXPOSE 3000